"""Install an `athena` shim on PATH so the CLI runs from any directory.

Writes a tiny launcher into a bin directory (default ``~/.local/bin``) that
hard-codes this install's root and Python, so it works regardless of the user's
cwd. This is the same shim the Athena desktop app drops on first run; running it
manually is for development or headless installs.
"""

from __future__ import annotations

import os
import stat
import sys
from pathlib import Path

from ._client import ROOT

MARKER = "# Generated by Athena (athena CLI shim)."


def _posix_shim(root: str, python: str) -> str:
    return (
        "#!/usr/bin/env bash\n"
        f"{MARKER} Re-run `athena install-cli` to update.\n"
        f'exec env PYTHONPATH="{root}${{PYTHONPATH:+:$PYTHONPATH}}" "{python}" -m cli "$@"\n'
    )


def _windows_shim(root: str, python: str) -> str:
    return f'@echo off\r\nrem {MARKER}\r\nset "PYTHONPATH={root};%PYTHONPATH%"\r\n"{python}" -m cli %*\r\n'


def install_cli(bin_dir: str | None = None, python: str | None = None) -> int:
    root = str(ROOT)
    python = python or sys.executable or ("python" if os.name == "nt" else "python3")

    if os.name == "nt":
        target_dir = Path(bin_dir).expanduser() if bin_dir else Path.home() / "AppData" / "Local" / "Athena" / "bin"
        target = target_dir / "athena.cmd"
        contents = _windows_shim(root, python)
    else:
        target_dir = Path(bin_dir).expanduser() if bin_dir else Path.home() / ".local" / "bin"
        target = target_dir / "athena"
        contents = _posix_shim(root, python)

    if target.exists() and MARKER not in target.read_text(encoding="utf-8", errors="replace"):
        print(f"error: {target} already exists and was not created by Athena; refusing to overwrite.", file=sys.stderr)
        print("       pass --bin-dir to choose another location.", file=sys.stderr)
        return 1

    target_dir.mkdir(parents=True, exist_ok=True)
    target.write_text(contents, encoding="utf-8")
    if os.name != "nt":
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"Installed `athena` -> {target}")
    print(f"  install root: {root}")
    print(f"  python:       {python}")

    if str(target_dir) not in os.environ.get("PATH", "").split(os.pathsep):
        print(f"\nNOTE: {target_dir} is not on your PATH. Add it, for example:")
        if os.name == "nt":
            print(f'  setx PATH "{target_dir};%PATH%"')
        else:
            print(f'  echo \'export PATH="{target_dir}:$PATH"\' >> ~/.bashrc && exec $SHELL')
    else:
        print("\nDone — run `athena` from any directory.")
    return 0
