import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { defaultPythonExecutable, isWindows } from "./platform.js";

// Drops a tiny `athena` launcher on the user's PATH so the CLI/TUI works from
// any directory after they install the desktop app. The shim hard-codes this
// install's resource root and Python, and preserves the caller's cwd. Mirrors
// the install-on-startup approach used by agent-skills.ts.

export type AthenaCliInstallStatus =
  | "installed"
  | "updated"
  | "unchanged"
  | "skipped"
  | "missing-source"
  | "error";

export type AthenaCliInstallResult = {
  status: AthenaCliInstallStatus;
  targetPath: string;
  sourceRoot: string | null;
  message?: string;
};

export type InstallAthenaCliOptions = {
  homeDir?: string;
  sourceRoot?: string | null;
  python?: string;
  targetPath?: string;
};

const MARKER = "# Generated by Athena (athena CLI shim).";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export function resolveBundledCliRoot(appRoot = path.resolve(__dirname, "..")): string | null {
  // The root that holds cli/, mcp_server/, and backend/ as siblings: the
  // resources dir when packaged, the repo root in development.
  const candidates = appRoot.includes(".asar")
    ? [path.dirname(appRoot)]
    : [path.resolve(appRoot, ".."), path.resolve(process.cwd(), ".."), process.cwd()];
  return (
    candidates.find(
      (candidate) =>
        fs.existsSync(path.join(candidate, "cli")) && fs.existsSync(path.join(candidate, "mcp_server")),
    ) ?? null
  );
}

export function defaultCliShimPath(homeDir: string): string {
  return isWindows
    ? path.join(homeDir, "AppData", "Local", "Athena", "bin", "athena.cmd")
    : path.join(homeDir, ".local", "bin", "athena");
}

function shimContents(root: string, python: string): string {
  if (isWindows) {
    return `@echo off\r\nrem ${MARKER}\r\nset "PYTHONPATH=${root};%PYTHONPATH%"\r\n"${python}" -m cli %*\r\n`;
  }
  return (
    `#!/usr/bin/env bash\n${MARKER}\n` +
    `exec env PYTHONPATH="${root}\${PYTHONPATH:+:$PYTHONPATH}" "${python}" -m cli "$@"\n`
  );
}

export function installAthenaCli(options: InstallAthenaCliOptions = {}): AthenaCliInstallResult {
  const homeDir = options.homeDir ?? os.homedir();
  const targetPath = options.targetPath ?? defaultCliShimPath(homeDir);
  try {
    const sourceRoot = options.sourceRoot ?? resolveBundledCliRoot();
    if (!sourceRoot) {
      return { status: "missing-source", targetPath, sourceRoot: null, message: "Bundled cli/ + mcp_server/ not found." };
    }

    const python = options.python ?? defaultPythonExecutable();
    const desired = shimContents(sourceRoot, python);

    if (fs.existsSync(targetPath)) {
      const current = fs.readFileSync(targetPath, "utf8");
      if (current === desired) {
        return { status: "unchanged", targetPath, sourceRoot };
      }
      // Never clobber an `athena` that Athena did not create.
      if (!current.includes(MARKER)) {
        return { status: "skipped", targetPath, sourceRoot, message: "Existing athena was not created by Athena." };
      }
      writeShim(targetPath, desired);
      return { status: "updated", targetPath, sourceRoot };
    }

    writeShim(targetPath, desired);
    return { status: "installed", targetPath, sourceRoot };
  } catch (error) {
    return {
      status: "error",
      targetPath,
      sourceRoot: options.sourceRoot ?? null,
      message: error instanceof Error ? error.message : String(error),
    };
  }
}

function writeShim(targetPath: string, contents: string): void {
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, contents, { encoding: "utf8", mode: 0o755 });
  if (!isWindows) {
    fs.chmodSync(targetPath, 0o755);
  }
}
