"""Refresh the project-local Hermes recall cache for Context Workspace.

This script is the default command behind CONTEXT_WORKSPACE_HERMES_REFRESH_CMD.
It intentionally writes the short-lived project recall cache directly so the
desktop app can refresh context even when Hermes-in-WSL cannot reach the
Windows backend loopback URL.
"""

from __future__ import annotations

import json
import os
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.agent_sessions import format_agent_sessions_summary, list_native_agent_sessions
from backend.safety import SafetyError, resolve_project_dir


SOURCE = "context-workspace-refresh-script"


def main() -> int:
    raw_project = os.environ.get("CONTEXT_WORKSPACE_PROJECT_DIR", "").strip()
    if not raw_project:
        print("CONTEXT_WORKSPACE_PROJECT_DIR is required.", file=sys.stderr)
        return 2

    try:
        project = _resolve_project(raw_project)
    except (OSError, SafetyError, ValueError) as exc:
        print(f"Invalid project directory: {exc}", file=sys.stderr)
        return 2

    task_hint = os.environ.get("CONTEXT_WORKSPACE_TASK_HINT", "").strip()
    backend_url = os.environ.get("CONTEXT_WORKSPACE_BACKEND_URL", "").strip()
    sessions = list_native_agent_sessions(project, query=task_hint, limit=25)
    if not sessions:
        sessions = list_native_agent_sessions(project, limit=10)

    markdown = _render_recall(project, task_hint=task_hint, backend_url=backend_url, sessions_summary=format_agent_sessions_summary(sessions))
    cache_dir = project / ".context-workspace" / "hermes"
    recall_path = cache_dir / "session-recall.md"
    metadata_path = cache_dir / "last-refresh.json"
    cache_dir.mkdir(parents=True, exist_ok=True)
    recall_path.write_text(markdown, encoding="utf-8")

    metadata: dict[str, Any] = {
        "refreshed_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
        "source": SOURCE,
        "bytes": len(markdown.encode("utf-8")),
        "task_hint": task_hint or None,
    }
    metadata_path.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")

    if not recall_path.exists() or not metadata_path.exists():
        print("Recall refresh did not produce expected cache files.", file=sys.stderr)
        return 1

    print(f"Recall refreshed: {recall_path}")
    print(f"Bytes: {metadata['bytes']}")
    return 0


def _resolve_project(project_dir: str) -> Path:
    try:
        return resolve_project_dir(project_dir)
    except SafetyError:
        translated = _wsl_mount_to_windows_path(project_dir)
        if translated == project_dir:
            raise
        return resolve_project_dir(translated)


def _wsl_mount_to_windows_path(project_dir: str) -> str:
    if os.name != "nt":
        return project_dir
    normalized = project_dir.replace("\\", "/")
    if not normalized.startswith("/mnt/") or len(normalized) < 8:
        return project_dir
    drive = normalized[5]
    if normalized[6] != "/" or not drive.isalpha():
        return project_dir
    rest = normalized[7:].replace("/", "\\")
    return f"{drive.upper()}:\\{rest}"


def _render_recall(project: Path, *, task_hint: str, backend_url: str, sessions_summary: str) -> str:
    now = datetime.now(UTC).isoformat().replace("+00:00", "Z")
    lines = [
        "# Hermes recall for Context Workspace",
        "",
        f"Generated by Context Workspace on {now}.",
        "",
        "## Current workspace",
        f"- Project: `{project}`",
    ]
    if task_hint:
        lines.append(f"- Task hint: {task_hint}")
    if backend_url:
        lines.append(f"- Backend: `{backend_url}`")
    lines.extend(
        [
            "",
            "## Operating contract",
            "- Hermes owns durable memory, config, policy, and session_search decisions.",
            "- Context Workspace owns app-side tools, session discovery, recall cache files, UI, and agent launch surfaces.",
            "- Agents should consume this generated recall as short-lived project context, not as a durable source of truth.",
            "",
            "## Native agent sessions",
            "",
            sessions_summary,
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
